# ================================
# âš™ï¸ MandoMC Global Settings
# ================================

# =================
# Database Options
# =================

DatabaseURL: ""
DatabaseUSER: ""
DatabasePASSWORD: ""

# These options control world behavior, gameplay restrictions, and mob activity.

# ================================
# ğŸš« Block Placement Restrictions
# ================================
# true = players CANNOT place this block
# false = players CAN place this block
disable-block-place:
  end_crystal: true
  end_portal_frame: true
  bedrock: true

# ================================
# ğŸš« Item & Gameplay Restrictions
# ================================
restrictions:
  # Prevents using / throwing ender pearls
  disable-enderpearls: true

  # Disables brewing stand interactions entirely
  disable-potion-brewing: true

  # Prevents villager trading GUI from opening
  disable-villager-trading: true

# ================================
# ğŸ›¡ï¸ Mob & Spawn Settings
# ================================
mobs:
  # Prevents phantoms from spawning naturally at night
  disable-natural-phantoms: true

# ================================
# â— Quest Settings
# ================================
quests:
  daily:
    number: 3
  weekly:
    number: 3

quest-npcs:
  reg-shop:
    custom-name:
      "{\"text\":\"Reg Shop\",\"strikethrough\":false,\"obfuscated\":false,\"bold\":true,\"italic\":false,\"underlined\":false,\"color\":\"gold\"}"
    quest:
      trigger:
        "open_reg_shop"
      amount:
        1.0

quest-commands:
  phone_home:
    quest:
      trigger:
        "phone_home"
      amount:
        1.0

quest-advancements:
  durasteel:
    quest:
      trigger:
        "durasteel"
      amount:
        1.0

# ================================
# ğŸŒ¸ Aesthetics
# ================================

tab:
  header: "&#ff0000&lMandoMC\n&7Star Wars Factions"
  footer: "&6play.mandomc.net\n&7Use /vote to get rewards!"

scoreboard:
  title: "&4&lMandoMC"
  lines:
    - "&7----------------"
    - "&6Â» &4&lFaction"
    - "     &câ†’ &o%factionsuuid_faction_name%"
    - "&6Â» &4&lPower"
    - "     &câ†’ &o%factionsuuid_faction_power% DTR"
    - "&6Â» &4&lBalance"
    - "     &câ†’ &o$%vault_eco_balance_formatted%"
    - "&7----------------"
    - "&6play.mandomc.net"

MOTD: '            &c&lMandoMC &7x &a&lOpen now! &7[1.21]                 &3Vehicles &7- &bForce Powers &7- &2Ewok Hunt &7- &aSabers'
VersionName: 'MandoMC 1.21'
ServerListHoverText:
  - "Â§7Â§m---------------------------Â§rÂ§cÂ§lMandoMCÂ§rÂ§7Â§m---------------------------"
  - "   Â§cSabers Â§7- Â§6Blasters Â§7- Â§eVehicles Â§7- Â§2Ewok Hunt Â§7- Â§bForce Powers Â§7- Â§dFactions"
  - "Â§7Â§m--------------------------------------------------------------"
  - "Â§fWebsite: Â§7- Â§aÂ§oComing soon..."
  - "Â§fDiscord: Â§7- Â§9discord.gg/3jGmpSddNt"
  - "Â§7Â§m--------------------------------------------------------------"
